name: n_collector_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas=3.0
  - tk=8.6
  - openpyxl=3.1
  - pyinstaller=6.18   # For wrapping to app
  # Standard Python library: os, datetime, dataclasses